# Safety CLI Firewall Policy Configuration
# Project: Clarity AI Backend - HIPAA Compliant FastAPI + ML/AI Stack
# Purpose: Real-time supply chain protection for development and CI/CD

# Security Configuration
security:
  # Vulnerability severity thresholds for blocking installations
  ignore-unpinned-requirements: false  # Enable checking unpinned dependencies
  
  # Fail builds/installations on these severity levels
  fail-on-severity:
    - "critical"
    - "high"
  
  # Continue with warnings for these severity levels  
  continue-on-severity:
    - "medium"
    - "low"
  
  # Ignore specific vulnerabilities if they're false positives or accepted risks
  # Format: ignore-vulnerabilities: ["12345", "67890"] 
  ignore-vulnerabilities: []

# License Compliance (Based on Task 2 findings)
licenses:
  # Block copyleft licenses that could affect proprietary code
  fail-on-license:
    - "GPL"
    - "GPLv2"
    - "GPLv2+"  
    - "GPLv3"
    - "GPLv3+"
    - "AGPL"
    - "AGPLv3"
  
  # Warn on LGPL licenses (require review but don't block)
  continue-on-license:
    - "LGPL"
    - "LGPLv2"
    - "LGPLv2+"
    - "LGPLv3"
    - "LGPLv3+"
  
  # Allow permissive licenses suitable for commercial/HIPAA use
  allow-license:
    - "MIT"
    - "MIT License"
    - "BSD"
    - "BSD License"
    - "BSD-2-Clause"
    - "BSD-3-Clause"
    - "Apache"
    - "Apache License"
    - "Apache Software License"
    - "Apache-2.0"
    - "Apache 2.0"
    - "ISC"
    - "ISC License"
    - "Unlicense"
    - "CC0"
    - "Public Domain"
    - "Python Software Foundation License"
    - "Mozilla Public License 2.0"

# Development Environment Protection
development:
  # Scan mode for development installs
  auto-scan: true
  
  # Block installations that fail policy
  fail-on-policy-violation: true
  
  # Log all scans for audit trail
  log-policy-violations: true

# CI/CD Integration Settings
cicd:
  # Strict mode for production builds
  strict-mode: true
  
  # Fail CI/CD on any policy violation
  fail-on-any-violation: true
  
  # Generate security reports
  generate-reports: true
  
  # Report formats
  report-formats:
    - "json"
    - "text"

# HIPAA Compliance Settings
hipaa:
  # Extra scrutiny for healthcare data protection
  enhanced-scanning: true
  
  # Require known licenses (block UNKNOWN)
  require-known-licenses: true
  
  # Block packages with known data leakage issues
  block-data-leakage-risks: true

# Package-specific overrides (based on our project needs)
package-overrides:
  # Known issues from our vulnerability baseline (Task 3)
  python-jose:
    # Block until vulnerabilities are addressed
    block: true
    reason: "Critical vulnerabilities detected in baseline scan (IDs: 70716, 70715)"
    
  # Development tools with GPL licenses (allow for dev-only)
  prospector:
    allow: true
    environment: "development"
    reason: "Development-only code analysis tool"
    
  pylint-django:
    allow: true  
    environment: "development"
    reason: "Development-only linting tool"
    
  pylint-plugin-utils:
    allow: true
    environment: "development" 
    reason: "Development-only linting utilities"

# Notification Settings
notifications:
  # Webhook for Slack/Teams integration (optional)
  webhook-url: null
  
  # Email notifications for policy violations
  email-notifications: false
  
  # Log file location for violations
  log-file: "logs/safety-policy-violations.log"

# Update and Maintenance
maintenance:
  # Auto-update vulnerability database
  auto-update-db: true
  
  # Policy review schedule (days)
  policy-review-interval: 30
  
  # Generate monthly compliance reports
  monthly-reports: true