"""
SQLAlchemy model for BiometricRule entity.

This module defines the database model for storing BiometricRule entities
using SQLAlchemy ORM. It represents the database schema and mapping for
biometric rules in the Novamind platform.
"""

import json
from datetime import datetime
from typing import Dict, Any, List
from uuid import UUID

from sqlalchemy import Column, String, Boolean, Text, ForeignKey, DateTime, JSON
from sqlalchemy.dialects.postgresql import UUID as PostgresUUID

from app.infrastructure.persistence.sqlalchemy.config.base import Base


class BiometricRuleModel(Base):
    """SQLAlchemy model for storing BiometricRule entities."""

    __tablename__ = "biometric_rules"

    # Core fields
    id = Column(
        PostgresUUID(as_uuid=True), 
        primary_key=True,
        doc="Unique identifier for the rule"
    )
    name = Column(
        String(255), 
        nullable=False,
        doc="Name of the rule"
    )
    description = Column(
        Text, 
        nullable=True,
        doc="Description of the rule"
    )
    
    # Rule configuration
    conditions = Column(
        JSON, 
        nullable=False,
        doc="JSON array of rule conditions"
    )
    logical_operator = Column(
        String(10), 
        nullable=False, 
        default="AND",
        doc="Logical operator to combine conditions (AND/OR)"
    )
    alert_priority = Column(
        String(20), 
        nullable=False,
        doc="Priority level for alerts generated by this rule"
    )
    is_active = Column(
        Boolean, 
        nullable=False, 
        default=True,
        doc="Whether the rule is currently active"
    )
    
    # Relationships
    patient_id = Column(
        PostgresUUID(as_uuid=True), 
        ForeignKey("patients.id", ondelete="CASCADE"), 
        nullable=True,
        doc="ID of the patient this rule is for (NULL for global rules)"
    )
    provider_id = Column(
        PostgresUUID(as_uuid=True), 
        ForeignKey("users.id", ondelete="SET NULL"), 
        nullable=True,
        doc="ID of the provider who created this rule"
    )
    
    # Metadata
    created_at = Column(
        DateTime, 
        nullable=False, 
        default=datetime.utcnow,
        doc="When the rule was created"
    )
    updated_at = Column(
        DateTime, 
        nullable=True,
        doc="When the rule was last updated"
    )
    rule_metadata = Column(
        JSON, 
        nullable=True,
        doc="Additional metadata for the rule"
    )

    def __repr__(self) -> str:
        """Get string representation of the model."""
        return f"<BiometricRuleModel(id={self.id}, name={self.name})>"
